"""create pengguna and sesi_login tables

Revision ID: e253a3107079
Revises: 
Create Date: 2026-10-02 19:08:39.733707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e253a3107079'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengguna',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('peran', sa.String(length=20), nullable=False),
    sa.Column('nomor_induk', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('kata_sandi', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=False),
    sa.Column('diubah_pada', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nomor_induk')
    )
    op.create_index(op.f('ix_pengguna_peran'), 'pengguna', ['peran'], unique=False)
    op.create_table('sesi_login',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pengguna_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('perangkat', sa.String(length=255), nullable=True),
    sa.Column('alamat_ip', sa.String(length=45), nullable=True),
    sa.Column('kedaluwarsa_pada', sa.DateTime(), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pengguna_id'], ['pengguna.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesi_login')
    op.drop_index(op.f('ix_pengguna_peran'), table_name='pengguna')
    op.drop_table('pengguna')
    # ### end Alembic commands ###
